# Generated by Django 3.2 on 2021-04-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_invoice_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
