# Generated by Django 3.2 on 2021-04-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_invoice_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='slug',
        ),
    ]
